### ISSUE TITLE
REJECTED_DESTINATION_NOT_REGISTERED

### ISSUE THREAD

**Issue by RyaiStudio** [infobip/infobip-api-php-tutorial#2]
hello 

I am using free account in infobip API and i try to to sent SMS using the code provided,
I'm trying to send SMS in multiple number's but i always get rejected response
the only number that success is the one that i registered from your free SMS account,
I don't find any link or form that can add recipient from the page.
I am new to develop this API and i don't have any idea on how it work's

**Comment by matijabruncic** [comment]
Hi,

This is expected behavior. As long as you use free account you can only send test SMS to your mobile phone. Please contact support@infobip.com to activate full account.

Best regards

**Comment by morask** [comment]
same problem at Whatsapp business api. No body response mails. No contact with infobip workers.
