### ISSUE TITLE
SendAt: Scheduled SMS does not deliver

### ISSUE THREAD

**Issue by ovvval** [infobip/infobip-api-php-tutorial#3]
I had been trying my hands on the API for sometime now ad I noticed that the messages sent with sendAt does not deliver.

I maybe doing something wrong so can you please clarify the way to do this successfully? I would appreciate  a sample code.

Thank you

**Comment by Antolius** [comment]
Hi!

It could be that you missed the date time format specified by the Infobip API. You can find detailed description of scheduling feature on the [dedicated documentation page](https://dev.infobip.com/docs/schedule-sms#schedule-sms-message).

PHP implementation would look something like this:
```
$myTimeZone = new DateTimeZone("Europe/London");
$tenMinutesInTheFuture = new DateTime("now +10 minute", $myTimeZone);
$apiDateTimeFormat = 'Y-m-d\TH:i:s.000P';
$sendAt = $tenMinutesInTheFuture->format($apiDateTimeFormat);

$message = array(
    "from" => $from,
    "destinations" => array($destination),
    "text" => $text,
    // any additional properties would come here
    "sendAt" => $sendAt
);
```

You can add the above snippet to this repo's [advancedSms.php](https://github.com/infobip/infobip-api-php-tutorial/blob/master/advancedSms.php#L122) file to see it in action.
Feel free to modify `DateTimeZone` and `DateTime` to reflect your use-case.

Note that the specified date time format is defined by the API.
If you are using PHP version 7.0.0 or later you can also try out this format:
`$apiDateTimeFormat = 'Y-m-d\TH:i:s.vP';`
It should provide added precision in the milliseconds range.
You can find out more about the format used above from the [PHP documentation page](http://php.net/manual/en/function.date.php#refsect1-function.date-parameters).

Hope this helps you with all your scheduling needs.
Feel free to contact us for any further assistance.

**Comment by ovvval** [comment]
Thank you @Antolius 

This is very helpful and handy.

I would be glad if you can help with this as well. In a case where the future date and time is submitted via a form, must I first calculate the difference between the time to deliver the message and the time now before passing it to $tenMinutesInTheFuture = new DateTime("now +10 minute", $myTimeZone); ?

> EG: the time the message is to deliver is 2017-03-30 18:30:00 and the form was submitted at 2017-03-27 03:31:19, how am I supposed to handle this?


 Thank you.

**Comment by Antolius** [comment]
There is no need to calculate the difference between now and the time to deliver the message.
API takes exact date time that you want the message to be delivered at.

If you have date submitted from a form you can use that to construct the `DateTime` object.
Your code might look like this:

```
//Let's say we received sendAt property from the form as a string in this format: "2017-03-27 09:55:15"
$sendAtDateTime= $_POST['sendAt'];

$myTimeZone = new DateTimeZone("Europe/Zagreb");
$apiDateTimeFormat = 'Y-m-d\TH:i:s.000P';

$sendAtDateTime = new DateTime($submittedSendAt, $myTimeZone);
$sendAt = $sendAtDateTime->format($apiDateTimeFormat);
```

For the list of formats that `DateTime` constructor can handle check out the [PHP documentation](http://php.net/manual/en/datetime.construct.php).

**Comment by ovvval** [comment]
Thank you so much for this answer. It worked perfectly.
