### ISSUE TITLE
Send To Many Sample Script in PHP

### ISSUE THREAD

**Issue by ovvval** [infobip/infobip-api-php-tutorial#4]
Hello @Antolius 

Thank you so much for helping me out with the scheduled messaging using the infobip api.

I have read the API doc but am currently facing this challenge.

My app queries a database and retrieves an array of telephone numbers. EG. $rec_list[];

I then wrote this code but it fails.

```
<?php
    
    /*
        $rec_list[]  is the an array of telephone numbers properly formatted
    */  

    $destination = array(
        "to" => $rec_list
    );
    $postDataJson = json_encode(
        array(
            "messages" => array(
                array(
                    "from" => $sender,
                    "destinations" => array($destination),
                    "text" => $message,
                    "sendAt" => $sendAt
                )
            )
        )
    );
?>
```

I will be glad if you can help me correct this code.

Thank you.

**Comment by Antolius** [comment]
Hi!

It's the `$destination` array that is the problem.
Let's say `$rec_list` contains 2 phone numbers, `"41793026731"` and `"41793026727"`.
Your code will produce the following json output:
```
{
   "messages":[
      {
         "from":"InfoSMS",
         "destinations":[
            {
               "to":[
                  "41793026731",
                  "41793026727"
               ]
            }
         ],
         "text":"A long time ago, in a galaxy far, far away...",
         "sendAt":"2017-07-07T17:00:00.000+01:00"
      }
   ]
}
```
whereas API is expecting json looking like this:
```
{
   "messages":[
      {
         "from":"InfoSMS",
         "destinations":[
            {
               "to":"41793026731"
            },
            {
               "to":"41793026727"
            }
         ],
         "text":"A long time ago, in a galaxy far, far away...",
         "sendAt":"2017-07-07T17:00:00.000+01:00"
      }
   ]
}
```
Notice that `destinations` part of a json should be an array with 2 elements, each of which is an object with the `to` property.
For reference check out the example in [send sms method's documentation page](https://dev.infobip.com/docs/fully-featured-textual-message).

**Comment by ovvval** [comment]
Thanks for your reply. 

I think what I am struggling with now is how to write the code to display the contacts from the database in this manner
```

        "destinations":[
            {
               "to":"41793026731"
            },
            {
               "to":"41793026727"
            }
         ],
```
Any help will be appreciated.

Thank you

**Comment by Antolius** [comment]
Official PHP documentation has a comprehensive tutorial on working with arrays.
You can find it at this link: http://php.net/manual/en/language.types.array.php

Generally, [official docs](http://php.net/manual/en/index.php) have many useful examples and you should be able to find answers to most of your PHP related questions there.

**Comment by ovvval** [comment]
Thanks buddy. Helpful

**Comment by Antolius** [comment]
Glad to have been of assistance!
