### ISSUE TITLE
Message Always Pending

### ISSUE THREAD

**Issue by Justicea83** [infobip/infobip-api-php-tutorial#6]
My message is always pending.
I simply cant figure it our

**Comment by denis-cutic** [comment]
Hi,

this status signals that we have successfully processed your request, sent it to a mobile operator and got an acknowledge from them, but are still waiting for a delivery report to come. 
In other words, we are waiting for the message to be delivered to a handset.

You can fetch the delivery report and check the end status of the message. The delivery report should be available within a minute or two. 

For more information please visit: https://dev.infobip.com/
