### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by Justicea83** [infobip/infobip-api-php-tutorial#7]
How do i callback after sending the sms successfully?

**Comment by Antolius** [comment]
[Last section](https://github.com/infobip/infobip-api-php-tutorial/tree/api-client-example#receive-delivery-report) of the tutorial deals with receiving SMS status in a callback from Infobip.

In this scenario Infobip will make an HTTP request to your server and [dlrPush.php](https://github.com/infobip/infobip-api-php-tutorial/blob/api-client-example/dlrPush.php) is an illustration of how you can handle those requests.
